name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check it out
      uses: actions/checkout@v2

    - name: Build and push Neptune image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: drtydogg/neptune
        directory: ./neptune
        dockerfile: ./neptune/Dockerfile
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
